StatCan/StatCan.OrchardCore

.github/workflows/build.yml, .github/workflows/release.yml
- Build that triggers on each push or PR
- Release that triggers when creating a GH release
=> Implement github actions

StatCan.OrchardCore.sln, src/Lib/StatCan.OrchardCore.Application.Targets/StatCan.OrchardCore.Application.Targets.csproj, src/Lib/StatCan.OrchardCore.Security/SecurityExtensions.cs, src/Modules/StatCan.OrchardCore.Matomo/AdminMenu.cs, src/Modules/StatCan.OrchardCore.Matomo/Drivers/MatomoSettingsDisplayDriver.cs, src/Modules/StatCan.OrchardCore.Matomo/Manifest.cs, src/Modules/StatCan.OrchardCore.Matomo/MatomoConstants.cs, src/Modules/StatCan.OrchardCore.Matomo/MatomoFilter.cs, src/Modules/StatCan.OrchardCore.Matomo/Permissions.cs, src/Modules/StatCan.OrchardCore.Matomo/Recipes/MatomoSettingsStep.cs, src/Modules/StatCan.OrchardCore.Matomo/Settings/MatomoSettings.cs, src/Modules/StatCan.OrchardCore.Matomo/Startup.cs, src/Modules/StatCan.OrchardCore.Matomo/StatCan.OrchardCore.Matomo.csproj, src/Modules/StatCan.OrchardCore.Matomo/ViewModels/MatomoSettingsViewModel.cs, src/Modules/StatCan.OrchardCore.Matomo/Views/MatomoSettings.Edit.cshtml, src/Modules/StatCan.OrchardCore.Matomo/Views/NavigationItemText-matomo.Id.cshtml, src/Modules/StatCan.OrchardCore.Matomo/Views/_ViewImports.cshtml
Closes #28
I had to modify the CSP script-src and img-src to allow *.statcan.ca and *.statcan.gc.ca for matomo to work.
=> feat(matomo): matomo analytics module

src/Modules/StatCan.OrchardCore.WebpageCore/Manifest.cs, src/Modules/StatCan.OrchardCore.WebpageCore/Migrations.cs, src/Modules/StatCan.OrchardCore.WebpageCore/Startup.cs, src/Themes/BootstrapTheme/Recipes/bootstrap.setup.recipe.json, src/Themes/DigitalAdmin/Views/Layout.cshtml, src/Themes/DigitalTheme/Recipes/digital.recipe.json, src/Themes/PortalTheme/Recipes/portal.recipe.json, test/cypress/integration/contact-form.js, test/cypress/integration/digital-theme.js, test/cypress/integration/portal-theme.js, test/cypress/integration/vue-form.js
=> Digital site improvements

src/Themes/DigitalTheme/Views/Widget-Section.liquid
This only prevented a some possible collisions.
=> fix: remove prefix

src/Lib/StatCan.OrchardCore.Security/SecurityExtensions.cs
=> feat: add materialdesignicons to csp

src/Themes/HackathonTheme/Recipes/hackathon.setup.recipe.json, src/Themes/HackathonTheme/Views/OrchardCore.Users/Account/ChangePassword.cshtml, src/Themes/HackathonTheme/Views/OrchardCore.Users/Account/ChangePasswordConfirmation.cshtml, src/Themes/HackathonTheme/Views/OrchardCore.Users/Account/Login.cshtml, src/Themes/HackathonTheme/Views/OrchardCore.Users/Registration/ConfirmEmail.cshtml, src/Themes/HackathonTheme/Views/OrchardCore.Users/Registration/Register.cshtml, src/Themes/HackathonTheme/Views/OrchardCore.Users/ResetPassword/ForgotPassword.cshtml, src/Themes/HackathonTheme/Views/OrchardCore.Users/ResetPassword/ForgotPasswordConfirmation.cshtml, src/Themes/HackathonTheme/Views/OrchardCore.Users/ResetPassword/ResetPassword.cshtml, src/Themes/HackathonTheme/Views/OrchardCore.Users/ResetPassword/ResetPasswordConfirmation.cshtml
=> feat: use vuetify components in login views

.github/workflows/translation.yml
See https://github.com/lukaskabrt/PoExtractor/issues/47 for bug
=> Extracting translation under windows was not working

src/Themes/DigitalAdmin/placement.json, src/Themes/HackathonTheme/HackathonTheme.csproj, src/Themes/HackathonTheme/Migrations.cs, src/Themes/HackathonTheme/Recipes/hackathon.setup.recipe.json, src/Themes/HackathonTheme/Views/Layout.liquid, src/Themes/HackathonTheme/Views/Widget-VAppBar.liquid, src/Themes/HackathonTheme/Views/Widget-VNavigationDrawer.liquid
VAppBar and VNavigationDrawer widgets created, used in Header and NavigationDrawer zones. Setup recipe updated to create these two with a default setting that makes sense.
=> Vappbar vnavigationdrawer widgets

src/Lib/StatCan.OrchardCore.Application.Targets/StatCan.OrchardCore.Application.Targets.csproj, src/Modules/StatCan.OrchardCore.EmailTemplates/AdminMenu.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Controllers/EmailTemplateController.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Deployment/AllEmailTemplatesDeploymentSource.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Deployment/AllEmailTemplatesDeploymentStep.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Deployment/AllEmailTemplatesDeploymentStepDriver.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Manifest.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Models/EmailTemplatesDocument.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Permissions.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Recipes/EmailTemplateStep.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Services/EmailTemplatesManager.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Startup.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/StatCan.OrchardCore.EmailTemplates.csproj, src/Modules/StatCan.OrchardCore.EmailTemplates/ViewModels/EmailTemplateIndexViewModel.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/ViewModels/EmailTemplateViewModel.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/ViewModels/SendEmailTemplateViewModel.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/EmailTemplate/Create.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/EmailTemplate/Edit.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/EmailTemplate/Index.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/EmailTemplate/SendEmail.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/Items/AllEmailTemplatesDeploymentStep.Edit.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/Items/AllEmailTemplatesDeploymentStep.Summary.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/Items/AllEmailTemplatesDeploymentStep.Thumbnail.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/_ViewImports.cshtml
fix #156 
This is the first step towards implementing email templates in Orchard. I will open tickets to add support for more ways to send emails using these templates.
=> feat: email template

src/Modules/StatCan.OrchardCore.Hackathon/Migrations/queries.recipe.json, src/Modules/StatCan.OrchardCore.Hackathon/Views/Widget-TeamDashboardWidget.liquid, src/Modules/StatCan.OrchardCore.Hackathon/Views/Widget-TeamJoinListWidget.liquid
Fixed the style for:
- TeamJoinListWidget
- TeamDashboardWidget
=> Fixed the style for the TeamDashboard and the TeamJoinList widgets

src/Modules/StatCan.OrchardCore.Hackathon/Views/Widget-TeamDashboardWidget.liquid, test/cypress/fixtures/recipes/team-management.json, test/cypress/fixtures/recipes/users.json, test/cypress/integration/hackathon.js
Fix #178 
Add test for the hackathon team management.
=> Hackathon Team Management Tests

src/Modules/StatCan.OrchardCore.EmailTemplates/Controllers/EmailTemplateController.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Services/EmailTemplatesService.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Services/IEmailTemplatesService.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Startup.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/StatCan.OrchardCore.EmailTemplates.csproj, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/Items/EmailTemplateTask.Fields.Design.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/Items/EmailTemplateTask.Fields.Edit.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/Items/EmailTemplateTask.Fields.Thumbnail.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Workflows/Activities/EmailTemplateTask.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Workflows/Drivers/EmailTemplateTaskDisplayDriver.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Workflows/ViewModels/EmailTemplateTaskViewModel.cs
fix #168 
Add a workflow task to send emails with templates
=> Email template workflow task

src/Modules/StatCan.OrchardCore.EmailTemplates/Controllers/EmailTemplateController.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Models/EmailTemplatesDocument.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Services/EmailTemplatesService.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Services/IEmailTemplatesService.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/ViewModels/EmailTemplateViewModel.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/ViewModels/SendEmailTemplateViewModel.cs, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/EmailTemplate/Create.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/EmailTemplate/Edit.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/EmailTemplate/SendEmail.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Views/Items/EmailTemplateTask.Fields.Edit.cshtml, src/Modules/StatCan.OrchardCore.EmailTemplates/Workflows/Activities/EmailTemplateTask.cs
Fix #166 
Add support for cc and bcc to EmailTemplates module.
=> Cc bcc email templates

src/Themes/HackathonTheme/Recipes/Schedule.recipe.json, src/Themes/HackathonTheme/Views/Widget-ScheduleEvent.liquid
DI-39
Modify the schedule widget and add a recipe that creates a demo schedule page
=> Schedules Page

docs/en/index.md, src/Build/Dependencies.props
Updating Orchard to `1.0.0-rc2-16128`
=> chore: update OC to 1.0.0-rc2-16128

docs/en/index.md, src/Build/Dependencies.props, src/Lib/StatCan.OrchardCore.Security/SecurityExtensions.cs
Orchard to 1.0.0-rc2-16143
SecurityHeaders to 0.14.0
Octokit to 0.50.0
=> chore: update dependencies

src/Modules/StatCan.OrchardCore.VueForms/Migrations.cs
Was missing an update for existing sites
=> fix: VueForm migrations to add the permission part

StatCan.OrchardCore.sln, docs/en/reference/modules/GraphQL.md, mkdocs.yml, src/Lib/StatCan.OrchardCore.Application.Targets/StatCan.OrchardCore.Application.Targets.csproj, src/Modules/StatCan.OrchardCore.Queries.GraphQL/AdminMenu.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Controllers/AdminController.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Drivers/GraphQLQueryDisplayDriver.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/GraphQLQuery.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/GraphQLQueryResults.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/GraphQLQuerySource.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Manifest.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Permissions.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Services/GraphQLQueryService.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Services/IGraphQLQueryService.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Startup.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/StatCan.OrchardCore.Queries.GraphQL.csproj, src/Modules/StatCan.OrchardCore.Queries.GraphQL/ViewModels/AdminQueryViewModel.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/ViewModels/GraphQLQueryViewModel.cs, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Views/Admin/Query.cshtml, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Views/GraphQLQuery.Buttons.SummaryAdmin.cshtml, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Views/GraphQLQuery.Edit.cshtml, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Views/GraphQLQuery.SummaryAdmin.cshtml, src/Modules/StatCan.OrchardCore.Queries.GraphQL/Views/_ViewImports.cshtml, test/cypress/fixtures/recipes/gql-query.json, test/cypress/integration/graphql-queries.js
This adds the ability to create Queries that use the GraphQL syntax
Todo: 
- Add GraphQL Syntax to Codemirror (edit: I tried and could not get it to work. Will refactor this later)
- Documentation
- Cypress test
- Recipe that create the query and a liquid page that displays the results
Make a PR to OC with these changes, I think this could be integrated in the core.
=> feat: GraphQL Queries

docs/en/reference/applications.md, docs/en/reference/modules/Hackathon.md, docs/en/reference/modules/Scheduling.md, mkdocs.yml
application modules provide out-of-the-box solutions for developers
added pages for existing application modules
=> docs: (#257) application modules

.github/workflows/pr_ci.yml, .github/workflows/release_ci.yml, docs/en/index.md, requirements.txt, src/Build/Dependencies.props
OC to 1.0.0-rc2-16216
mkdocs to 7.1.5
dotnet build to 5.0.*
=> chore: dependency updates

src/Apps/StatCan.OrchardCore.Scheduling/Views/Content-AppointmentCalendar.liquid
In some cases, a comma was missing.
=> fix: bug with missing comma in some cases

src/Apps/StatCan.OrchardCore.Scheduling/Migrations.cs, src/Apps/StatCan.OrchardCore.Scheduling/Migrations/initial.recipe.json, src/Apps/StatCan.OrchardCore.Scheduling/Views/Calendar.liquid
=> fix: add  configuration for the calendar
